/*
 * asn1vn.c -- read DER from stdin, decode it as the -DPDU root type, and write
 * ASN.1 value notation to stdout.
 *
 * Shaped like asn1c's converter-example, but with vn_encode as the output stage.
 * The root type arrives at compile time via -DPDU=<TypeName>.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <asn_application.h>
#include "vn_encoder.h"

/*
 * Value assignments are module syntax, not value syntax, so the codec knows
 * nothing about them: skipping `valueN <Type> ::= ` is the tool's job. Returns
 * the offset just past the header, or `pos` when there is none.
 *
 * X.680 comments and whitespace may appear anywhere, so both are skipped here
 * too -- the same rules the tokeniser applies inside a value.
 */
static size_t
skip_filler(const char *buf, size_t len, size_t pos) {
    for(;;) {
        while(pos < len && (buf[pos] == ' ' || buf[pos] == '\t'
                            || buf[pos] == '\n' || buf[pos] == '\r'))
            pos++;
        if(pos + 1 < len && buf[pos] == '-' && buf[pos + 1] == '-') {
            pos += 2;
            while(pos < len) {
                if(buf[pos] == '\n') { pos++; break; }
                if(pos + 1 < len && buf[pos] == '-' && buf[pos + 1] == '-') {
                    pos += 2;
                    break;
                }
                pos++;
            }
            continue;
        }
        return pos;
    }
}

static size_t
take_ident(const char *buf, size_t len, size_t pos) {
    size_t start = pos;
    while(pos < len
          && ((buf[pos] >= 'a' && buf[pos] <= 'z')
              || (buf[pos] >= 'A' && buf[pos] <= 'Z')
              || (buf[pos] >= '0' && buf[pos] <= '9') || buf[pos] == '-'
              || buf[pos] == '_'))
        pos++;
    return pos > start ? pos : start;
}

static size_t
skip_assignment_header(const char *buf, size_t len, size_t pos) {
    size_t p = skip_filler(buf, len, pos), q;

    q = take_ident(buf, len, p);
    if(q == p) return pos; /* no value reference */
    p = skip_filler(buf, len, q);
    q = take_ident(buf, len, p);
    if(q == p) return pos; /* no type reference */
    p = skip_filler(buf, len, q);
    if(p + 2 < len && buf[p] == ':' && buf[p + 1] == ':' && buf[p + 2] == '=')
        return p + 3;
    return pos;
}

#define VN_CAT_(a, b) a##b
#define VN_CAT(a, b) VN_CAT_(a, b)
#define VN_PDU_DEF VN_CAT(asn_DEF_, PDU)

extern asn_TYPE_descriptor_t VN_PDU_DEF;

/* Empty unless a table generated by vn-annotate is linked in. */
extern const vn_annotations_t vn_generated_annotations;

static int
vn_write_der(const void *data, size_t size, void *key) {
    return fwrite(data, 1, size, (FILE *)key) == size ? 0 : -1;
}

static void
usage(const char *argv0) {
    fprintf(stderr,
            "usage: %s [-c|-a] [-A] [-l WIDTH] [-i WIDTH] [-L] [-S] < input.der\n"
            "\n"
            "  -c        canonical output: deterministic, for diffing\n"
            "  -a        annotated output: adds X.680 comments\n"
            "  -A        emit value assignments: `valueN <Type> ::= <value>`,\n"
            "            the form reference tooling uses, instead of bare values\n"
            "  -l WIDTH  wrap hex at WIDTH columns; 0 disables wrapping\n"
            "  -i WIDTH  indent width, default 4\n"
            "  -L        lenient: emit questionable values instead of failing\n"
            "  -S        strict: fail on a bare ANY rather than emitting hex\n"
            "\n"
            "  -r        reverse: read value notation on stdin, write DER on\n"
            "            stdout. Accepts bare values and `valueN <Type> ::= ...`\n"
            "            assignments, one after another, as reference tooling\n"
            "            emits them.\n",
            argv0);
}

int
main(int argc, char **argv) {
    vn_options_t opts;
    char reason[256] = "";
    unsigned char *buf;
    size_t cap = 1 << 16, len = 0, n, offset, count = 0;
    void *st = 0;
    asn_dec_rval_t rv;
    int i, assignments = 0, reverse = 0;

    memset(&opts, 0, sizeof opts);
    opts.mode = VN_MODE_PRETTY;
    opts.annotations = &vn_generated_annotations;
    opts.errbuf = reason;
    opts.errlen = sizeof reason;

    for(i = 1; i < argc; i++) {
        if(!strcmp(argv[i], "-c")) {
            opts.mode = VN_MODE_CANONICAL;
        } else if(!strcmp(argv[i], "-a")) {
            opts.mode = VN_MODE_ANNOTATED;
        } else if(!strcmp(argv[i], "-L")) {
            opts.flags |= VN_F_LENIENT;
        } else if(!strcmp(argv[i], "-S")) {
            opts.flags |= VN_F_STRICT_ANY;
        } else if(!strcmp(argv[i], "-A")) {
            assignments = 1;
        } else if(!strcmp(argv[i], "-r")) {
            reverse = 1;
        } else if(!strcmp(argv[i], "-l") && i + 1 < argc) {
            opts.line_width = atoi(argv[++i]);
            if(opts.line_width == 0) opts.line_width = -1; /* 0 means default */
        } else if(!strcmp(argv[i], "-i") && i + 1 < argc) {
            opts.indent_width = atoi(argv[++i]);
        } else {
            usage(argv[0]);
            return 2;
        }
    }
    /* vn_options_t treats 0 as "use the default", so -l 0 arrives as -1 and is
     * translated to a width that disables wrapping. */
    if(opts.line_width < 0) opts.line_width = 1 << 24;

    buf = (unsigned char *)malloc(cap);
    if(!buf) {
        perror("malloc");
        return 2;
    }
    while((n = fread(buf + len, 1, cap - len, stdin)) > 0) {
        len += n;
        if(len == cap) {
            unsigned char *nb = (unsigned char *)realloc(buf, cap * 2);
            if(!nb) {
                perror("realloc");
                free(buf);
                return 2;
            }
            buf = nb;
            cap *= 2;
        }
    }
    if(ferror(stdin)) {
        perror("read");
        free(buf);
        return 2;
    }

    if(reverse) {
        /*
         * Value notation in, DER out. Reads as many values as the input holds,
         * so a file of assignments becomes the concatenated encodings -- which is
         * what an SGP.22 profile package is.
         */
        vn_read_options_t ro;
        size_t            off = 0, count_r = 0;

        memset(&ro, 0, sizeof ro);
        ro.flags = VN_RF_EOF; /* the whole text is in the buffer */
        ro.annotations = &vn_generated_annotations;
        ro.errbuf = reason;
        ro.errlen = sizeof reason;

        for(;;) {
            asn_dec_rval_t dv;
            asn_enc_rval_t ev;

            off = skip_filler((const char *)buf, len, off);
            if(off >= len) break;
            off = skip_assignment_header((const char *)buf, len, off);
            off = skip_filler((const char *)buf, len, off);
            if(off >= len) break;

            st = 0;
            dv = vn_decode(0, &VN_PDU_DEF, &st, &ro, buf + off, len - off);
            if(dv.code != RC_OK) {
                fprintf(stderr, "%s: cannot read value %lu: %s\n", argv[0],
                        (unsigned long)count_r + 1,
                        reason[0] ? reason : "unknown error");
                if(st) ASN_STRUCT_FREE(VN_PDU_DEF, st);
                free(buf);
                return 1;
            }
            ev = der_encode(&VN_PDU_DEF, st, vn_write_der, stdout);
            ASN_STRUCT_FREE(VN_PDU_DEF, st);
            if(ev.encoded < 0) {
                fprintf(stderr, "%s: cannot encode value %lu as DER\n", argv[0],
                        (unsigned long)count_r + 1);
                free(buf);
                return 1;
            }
            off += dv.consumed;
            count_r++;
        }

        free(buf);
        if(count_r == 0) {
            fprintf(stderr, "%s: no value notation found on stdin\n", argv[0]);
            return 1;
        }
        if(fflush(stdout) != 0) {
            perror("write");
            return 1;
        }
        return 0;
    }

    /*
     * Decode every PDU in the input, not just the first.
     *
     * A single DER value is the common case, but some formats concatenate them:
     * an SGP.22 profile package is a sequence of ProfileElement TLVs one after
     * another, so stopping after one would silently ignore almost the whole
     * file. Each value is emitted in turn; with more than one, the output is a
     * sequence of X.680 values rather than a single value.
     */
    for(offset = 0; offset < len; count++) {
        st = 0;
        rv = asn_decode(0, ATS_BER, &VN_PDU_DEF, &st, buf + offset,
                        len - offset);
        if(rv.code != RC_OK) {
            fprintf(stderr,
                    "%s: BER/DER decode failed (code %d) at byte %lu of %lu",
                    argv[0], (int)rv.code, (unsigned long)(offset + rv.consumed),
                    (unsigned long)len);
            if(count) fprintf(stderr, ", after %lu value(s)", (unsigned long)count);
            fputc('\n', stderr);
            if(st) ASN_STRUCT_FREE(VN_PDU_DEF, st);
            free(buf);
            return 1;
        }
        if(rv.consumed == 0) { /* no progress: refuse to loop forever */
            fprintf(stderr, "%s: decoder consumed no input at byte %lu\n",
                    argv[0], (unsigned long)offset);
            if(st) ASN_STRUCT_FREE(VN_PDU_DEF, st);
            free(buf);
            return 1;
        }

        if(count && fputc('\n', stdout) == EOF) {
            perror("write");
            ASN_STRUCT_FREE(VN_PDU_DEF, st);
            free(buf);
            return 1;
        }
        if(opts.mode == VN_MODE_ANNOTATED && !assignments
           && printf("-- value %lu at byte %lu --\n", (unsigned long)count + 1,
                     (unsigned long)offset)
                  < 0) {
            perror("write");
            ASN_STRUCT_FREE(VN_PDU_DEF, st);
            free(buf);
            return 1;
        }
        /* `valueN <Type> ::= ` -- a full X.680 value assignment, the form
         * reference tooling emits, so its output can be diffed directly. */
        if(assignments
           && printf("value%lu %s ::= ", (unsigned long)count + 1,
                     VN_PDU_DEF.name ? VN_PDU_DEF.name : "Value")
                  < 0) {
            perror("write");
            ASN_STRUCT_FREE(VN_PDU_DEF, st);
            free(buf);
            return 1;
        }
        if(vn_fprint(stdout, &VN_PDU_DEF, st, &opts) < 0) {
            fprintf(stderr, "%s: cannot render value notation: %s\n", argv[0],
                    reason[0] ? reason : "unknown error");
            ASN_STRUCT_FREE(VN_PDU_DEF, st);
            free(buf);
            return 1;
        }
        fputc('\n', stdout);

        ASN_STRUCT_FREE(VN_PDU_DEF, st);
        offset += rv.consumed;
    }

    free(buf);
    if(count == 0) {
        fprintf(stderr, "%s: input is empty\n", argv[0]);
        return 1;
    }
    if(fflush(stdout) != 0) {
        perror("write");
        return 1;
    }
    return 0;
}
